### ISSUE TITLE
Injecting scarface_dinput.dll

### ISSUE THREAD

**Issue by Keith94** [aap/XDinput#1]
Hi @aap,
I tried to use UAL, as your readme states, to inject `scarface_dinput.dll` into the game. However, UAL comes named as `dinput8.dll`, which conflicts with your XDinput, and renaming it to `d3d9.dll` also conflicts with dgVoodoo (essential fix). Any ideas how to get everything working nicely together?

**Comment by elishacloud** [comment]
You can use dxwrapper to inject `scarface_dinput.dll` into the game.  However, this will require more than just injecting `scarface_dinput.dll` into a game.  The game also needs to use the APIs in this dll.  You could do that by hooking the `dinput8.dll` APIs and redirecting them to `scarface_dinput.dll`.

Another option would be to change the registry so that `CoCreateInstance` would attempt to load the local instance of the `dinput8.dll` before trying the System32 dll.  Then you could just rename `scarface_dinput.dll` to `dinput8.dll` and put it in the game folder.

However, if you want to try with dxwrapper then you can follow the steps below.  It might work if the game loads `d3d9.dll` before calling `CoCreateInstance`.  I already created a package for you.  This package includes the latest dgVoodoo2 `d3d9.dll` in it, renamed to `dg_d3d9.dll`.  I preconfigured dxwrapper to redirect `d3d9.dll` to `dg_d3d9.dll`.  I also configured dxwrapper to load `dinput8.dll`.

Steps:
1. Download and unzip the package into the game folder: [dg_d3d9.zip](https://github.com/aap/XDinput/files/3777342/dg_d3d9.zip).
2. Rename `scarface_dinput.dll` to `dinput8.dll` and copy it to the game folder.

**Comment by Keith94** [comment]
@elishacloud Thanks for the reply!

I followed your steps, but it seems the game still isn't detecting the triggers in game.

```
10640 00:05:39.642 Starting DxWrapper v1.0.6334.21
10640 00:05:39.642 ASUSTeK COMPUTER INC. SABERTOOTH Z77 Rev 1.xx (Desktop)
10640 00:05:39.643 NVIDIA GeForce GTX 680
10640 00:05:39.643 Windows 10 64-bit (10.0.18362) 
10640 00:05:39.643 "Scarface.exe" (PID:3628)
10640 00:05:39.648 Wrapping 'd3d9.dll'...
10640 00:05:39.648 Loading 'dg_d3d9.dll' as real dll...
10640 00:05:39.652 Loaded library: kernel32.dll
10640 00:05:39.652 Hooking 'GetProcAddress' API...
10640 00:05:39.652 Disabling High DPI Scaling...
10640 00:05:39.652 Loaded library: user32.dll
10640 00:05:39.652 Loaded library: shcore.dll
10640 00:05:39.684 Loaded library: C:\WINDOWS\system32\dinput8.dll
10640 00:05:39.684 DxWrapper loaded!
10640 00:06:44.864 Quiting DxWrapper
10640 00:06:44.864 Unloading libraries...
10640 00:06:44.864 Reseting screen resolution
10640 00:06:44.877 Reseting font smoothing
10640 00:06:44.881 DxWrapper terminated!
```

**Comment by aap** [comment]
I use UAL as vorbisfile.dll

**Comment by Keith94** [comment]
I forgot to also use dinput8.dll from XDinput/bin/ in my previous post...

>I use UAL as vorbisfile.dll

This got it to load, so I can assign the triggers in game. However, now if I use the triggers during gameplay, it crashes my game.

**Comment by aap** [comment]
The crash is probably due to vibration. I dunno why it happens but if you disable it, I think it'll work. Also you shouldn't have to reassign anything unless you don't want PS2 controls.

**Comment by Keith94** [comment]
>I dunno why it happens but if you disable it, I think it'll work.

Yeah, that works! I guess we have to play without vibration then.

**Comment by aap** [comment]
Or you fix my code :)

**Comment by Keith94** [comment]
Thanks for the help!
